apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: razorbill-backend
spec:
  rules:
    - host: backend.local # 👈 replace with your real domain later
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: razorbill-backend
                port:
                  number: 3001
