apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  OPENROUTER_API_KEY: c2stb3ItdjEtYmEwYTMxMjllOWU1OTVhNGY1ZDk1ZTk1ZTc2YTZjZDJhYzkxMmZjYzVhZjI0ZjQzYWQ2Mzc1NTY2Y2RkMTg1Yg==
